name: three
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.2.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

flutter:
    uses-material-design: true
dev_dependencies:
  flutter_test:
    sdk: flutter

# ...
